spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://my-vedadev.postgres.database.azure.com:5432/veda
    username: njt_005@my-vedadev
    password: njt_005
  logging:
    level:
      root: DEBUG
      com.example.repository: DEBUG
      com.example: DEBUG