package com.example.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TShippingPackageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    public TShippingPackageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShippingInstructionNoIsNull() {
            addCriterion("shipping_instruction_no is null");
            return (Criteria) this;
        }

        public Criteria andShippingInstructionNoIsNotNull() {
            addCriterion("shipping_instruction_no is not null");
            return (Criteria) this;
        }

        public Criteria andShippingInstructionNoEqualTo(Integer value) {
            addCriterion("shipping_instruction_no =", value, "shippingInstructionNo");
            return (Criteria) this;
        }

        public Criteria andShippingInstructionNoNotEqualTo(Integer value) {
            addCriterion("shipping_instruction_no <>", value, "shippingInstructionNo");
            return (Criteria) this;
        }

        public Criteria andShippingInstructionNoGreaterThan(Integer value) {
            addCriterion("shipping_instruction_no >", value, "shippingInstructionNo");
            return (Criteria) this;
        }

        public Criteria andShippingInstructionNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("shipping_instruction_no >=", value, "shippingInstructionNo");
            return (Criteria) this;
        }

        public Criteria andShippingInstructionNoLessThan(Integer value) {
            addCriterion("shipping_instruction_no <", value, "shippingInstructionNo");
            return (Criteria) this;
        }

        public Criteria andShippingInstructionNoLessThanOrEqualTo(Integer value) {
            addCriterion("shipping_instruction_no <=", value, "shippingInstructionNo");
            return (Criteria) this;
        }

        public Criteria andShippingInstructionNoIn(List<Integer> values) {
            addCriterion("shipping_instruction_no in", values, "shippingInstructionNo");
            return (Criteria) this;
        }

        public Criteria andShippingInstructionNoNotIn(List<Integer> values) {
            addCriterion("shipping_instruction_no not in", values, "shippingInstructionNo");
            return (Criteria) this;
        }

        public Criteria andShippingInstructionNoBetween(Integer value1, Integer value2) {
            addCriterion("shipping_instruction_no between", value1, value2, "shippingInstructionNo");
            return (Criteria) this;
        }

        public Criteria andShippingInstructionNoNotBetween(Integer value1, Integer value2) {
            addCriterion("shipping_instruction_no not between", value1, value2, "shippingInstructionNo");
            return (Criteria) this;
        }

        public Criteria andWnoIsNull() {
            addCriterion("wno is null");
            return (Criteria) this;
        }

        public Criteria andWnoIsNotNull() {
            addCriterion("wno is not null");
            return (Criteria) this;
        }

        public Criteria andWnoEqualTo(String value) {
            addCriterion("wno =", value, "wno");
            return (Criteria) this;
        }

        public Criteria andWnoNotEqualTo(String value) {
            addCriterion("wno <>", value, "wno");
            return (Criteria) this;
        }

        public Criteria andWnoGreaterThan(String value) {
            addCriterion("wno >", value, "wno");
            return (Criteria) this;
        }

        public Criteria andWnoGreaterThanOrEqualTo(String value) {
            addCriterion("wno >=", value, "wno");
            return (Criteria) this;
        }

        public Criteria andWnoLessThan(String value) {
            addCriterion("wno <", value, "wno");
            return (Criteria) this;
        }

        public Criteria andWnoLessThanOrEqualTo(String value) {
            addCriterion("wno <=", value, "wno");
            return (Criteria) this;
        }

        public Criteria andWnoLike(String value) {
            addCriterion("wno like", value, "wno");
            return (Criteria) this;
        }

        public Criteria andWnoNotLike(String value) {
            addCriterion("wno not like", value, "wno");
            return (Criteria) this;
        }

        public Criteria andWnoIn(List<String> values) {
            addCriterion("wno in", values, "wno");
            return (Criteria) this;
        }

        public Criteria andWnoNotIn(List<String> values) {
            addCriterion("wno not in", values, "wno");
            return (Criteria) this;
        }

        public Criteria andWnoBetween(String value1, String value2) {
            addCriterion("wno between", value1, value2, "wno");
            return (Criteria) this;
        }

        public Criteria andWnoNotBetween(String value1, String value2) {
            addCriterion("wno not between", value1, value2, "wno");
            return (Criteria) this;
        }

        public Criteria andPackageNoIsNull() {
            addCriterion("package_no is null");
            return (Criteria) this;
        }

        public Criteria andPackageNoIsNotNull() {
            addCriterion("package_no is not null");
            return (Criteria) this;
        }

        public Criteria andPackageNoEqualTo(String value) {
            addCriterion("package_no =", value, "packageNo");
            return (Criteria) this;
        }

        public Criteria andPackageNoNotEqualTo(String value) {
            addCriterion("package_no <>", value, "packageNo");
            return (Criteria) this;
        }

        public Criteria andPackageNoGreaterThan(String value) {
            addCriterion("package_no >", value, "packageNo");
            return (Criteria) this;
        }

        public Criteria andPackageNoGreaterThanOrEqualTo(String value) {
            addCriterion("package_no >=", value, "packageNo");
            return (Criteria) this;
        }

        public Criteria andPackageNoLessThan(String value) {
            addCriterion("package_no <", value, "packageNo");
            return (Criteria) this;
        }

        public Criteria andPackageNoLessThanOrEqualTo(String value) {
            addCriterion("package_no <=", value, "packageNo");
            return (Criteria) this;
        }

        public Criteria andPackageNoLike(String value) {
            addCriterion("package_no like", value, "packageNo");
            return (Criteria) this;
        }

        public Criteria andPackageNoNotLike(String value) {
            addCriterion("package_no not like", value, "packageNo");
            return (Criteria) this;
        }

        public Criteria andPackageNoIn(List<String> values) {
            addCriterion("package_no in", values, "packageNo");
            return (Criteria) this;
        }

        public Criteria andPackageNoNotIn(List<String> values) {
            addCriterion("package_no not in", values, "packageNo");
            return (Criteria) this;
        }

        public Criteria andPackageNoBetween(String value1, String value2) {
            addCriterion("package_no between", value1, value2, "packageNo");
            return (Criteria) this;
        }

        public Criteria andPackageNoNotBetween(String value1, String value2) {
            addCriterion("package_no not between", value1, value2, "packageNo");
            return (Criteria) this;
        }

        public Criteria andShippingNoIsNull() {
            addCriterion("shipping_no is null");
            return (Criteria) this;
        }

        public Criteria andShippingNoIsNotNull() {
            addCriterion("shipping_no is not null");
            return (Criteria) this;
        }

        public Criteria andShippingNoEqualTo(String value) {
            addCriterion("shipping_no =", value, "shippingNo");
            return (Criteria) this;
        }

        public Criteria andShippingNoNotEqualTo(String value) {
            addCriterion("shipping_no <>", value, "shippingNo");
            return (Criteria) this;
        }

        public Criteria andShippingNoGreaterThan(String value) {
            addCriterion("shipping_no >", value, "shippingNo");
            return (Criteria) this;
        }

        public Criteria andShippingNoGreaterThanOrEqualTo(String value) {
            addCriterion("shipping_no >=", value, "shippingNo");
            return (Criteria) this;
        }

        public Criteria andShippingNoLessThan(String value) {
            addCriterion("shipping_no <", value, "shippingNo");
            return (Criteria) this;
        }

        public Criteria andShippingNoLessThanOrEqualTo(String value) {
            addCriterion("shipping_no <=", value, "shippingNo");
            return (Criteria) this;
        }

        public Criteria andShippingNoLike(String value) {
            addCriterion("shipping_no like", value, "shippingNo");
            return (Criteria) this;
        }

        public Criteria andShippingNoNotLike(String value) {
            addCriterion("shipping_no not like", value, "shippingNo");
            return (Criteria) this;
        }

        public Criteria andShippingNoIn(List<String> values) {
            addCriterion("shipping_no in", values, "shippingNo");
            return (Criteria) this;
        }

        public Criteria andShippingNoNotIn(List<String> values) {
            addCriterion("shipping_no not in", values, "shippingNo");
            return (Criteria) this;
        }

        public Criteria andShippingNoBetween(String value1, String value2) {
            addCriterion("shipping_no between", value1, value2, "shippingNo");
            return (Criteria) this;
        }

        public Criteria andShippingNoNotBetween(String value1, String value2) {
            addCriterion("shipping_no not between", value1, value2, "shippingNo");
            return (Criteria) this;
        }

        public Criteria andTotalCoilQuantityIsNull() {
            addCriterion("total_coil_quantity is null");
            return (Criteria) this;
        }

        public Criteria andTotalCoilQuantityIsNotNull() {
            addCriterion("total_coil_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCoilQuantityEqualTo(Integer value) {
            addCriterion("total_coil_quantity =", value, "totalCoilQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCoilQuantityNotEqualTo(Integer value) {
            addCriterion("total_coil_quantity <>", value, "totalCoilQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCoilQuantityGreaterThan(Integer value) {
            addCriterion("total_coil_quantity >", value, "totalCoilQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCoilQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_coil_quantity >=", value, "totalCoilQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCoilQuantityLessThan(Integer value) {
            addCriterion("total_coil_quantity <", value, "totalCoilQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCoilQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("total_coil_quantity <=", value, "totalCoilQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCoilQuantityIn(List<Integer> values) {
            addCriterion("total_coil_quantity in", values, "totalCoilQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCoilQuantityNotIn(List<Integer> values) {
            addCriterion("total_coil_quantity not in", values, "totalCoilQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCoilQuantityBetween(Integer value1, Integer value2) {
            addCriterion("total_coil_quantity between", value1, value2, "totalCoilQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCoilQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("total_coil_quantity not between", value1, value2, "totalCoilQuantity");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNull() {
            addCriterion("delete_flg is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNotNull() {
            addCriterion("delete_flg is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgEqualTo(String value) {
            addCriterion("delete_flg =", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotEqualTo(String value) {
            addCriterion("delete_flg <>", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThan(String value) {
            addCriterion("delete_flg >", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThanOrEqualTo(String value) {
            addCriterion("delete_flg >=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThan(String value) {
            addCriterion("delete_flg <", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThanOrEqualTo(String value) {
            addCriterion("delete_flg <=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLike(String value) {
            addCriterion("delete_flg like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotLike(String value) {
            addCriterion("delete_flg not like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIn(List<String> values) {
            addCriterion("delete_flg in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotIn(List<String> values) {
            addCriterion("delete_flg not in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgBetween(String value1, String value2) {
            addCriterion("delete_flg between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotBetween(String value1, String value2) {
            addCriterion("delete_flg not between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeEqualTo(LocalDateTime value) {
            addCriterion("create_datetime =", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_datetime <>", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("create_datetime >", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_datetime >=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThan(LocalDateTime value) {
            addCriterion("create_datetime <", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_datetime <=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIn(List<LocalDateTime> values) {
            addCriterion("create_datetime in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_datetime not in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_datetime between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_datetime not between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateSessionIsNull() {
            addCriterion("create_session is null");
            return (Criteria) this;
        }

        public Criteria andCreateSessionIsNotNull() {
            addCriterion("create_session is not null");
            return (Criteria) this;
        }

        public Criteria andCreateSessionEqualTo(String value) {
            addCriterion("create_session =", value, "createSession");
            return (Criteria) this;
        }

        public Criteria andCreateSessionNotEqualTo(String value) {
            addCriterion("create_session <>", value, "createSession");
            return (Criteria) this;
        }

        public Criteria andCreateSessionGreaterThan(String value) {
            addCriterion("create_session >", value, "createSession");
            return (Criteria) this;
        }

        public Criteria andCreateSessionGreaterThanOrEqualTo(String value) {
            addCriterion("create_session >=", value, "createSession");
            return (Criteria) this;
        }

        public Criteria andCreateSessionLessThan(String value) {
            addCriterion("create_session <", value, "createSession");
            return (Criteria) this;
        }

        public Criteria andCreateSessionLessThanOrEqualTo(String value) {
            addCriterion("create_session <=", value, "createSession");
            return (Criteria) this;
        }

        public Criteria andCreateSessionLike(String value) {
            addCriterion("create_session like", value, "createSession");
            return (Criteria) this;
        }

        public Criteria andCreateSessionNotLike(String value) {
            addCriterion("create_session not like", value, "createSession");
            return (Criteria) this;
        }

        public Criteria andCreateSessionIn(List<String> values) {
            addCriterion("create_session in", values, "createSession");
            return (Criteria) this;
        }

        public Criteria andCreateSessionNotIn(List<String> values) {
            addCriterion("create_session not in", values, "createSession");
            return (Criteria) this;
        }

        public Criteria andCreateSessionBetween(String value1, String value2) {
            addCriterion("create_session between", value1, value2, "createSession");
            return (Criteria) this;
        }

        public Criteria andCreateSessionNotBetween(String value1, String value2) {
            addCriterion("create_session not between", value1, value2, "createSession");
            return (Criteria) this;
        }

        public Criteria andCreateIpIsNull() {
            addCriterion("create_ip is null");
            return (Criteria) this;
        }

        public Criteria andCreateIpIsNotNull() {
            addCriterion("create_ip is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIpEqualTo(String value) {
            addCriterion("create_ip =", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpNotEqualTo(String value) {
            addCriterion("create_ip <>", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpGreaterThan(String value) {
            addCriterion("create_ip >", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpGreaterThanOrEqualTo(String value) {
            addCriterion("create_ip >=", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpLessThan(String value) {
            addCriterion("create_ip <", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpLessThanOrEqualTo(String value) {
            addCriterion("create_ip <=", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpLike(String value) {
            addCriterion("create_ip like", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpNotLike(String value) {
            addCriterion("create_ip not like", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpIn(List<String> values) {
            addCriterion("create_ip in", values, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpNotIn(List<String> values) {
            addCriterion("create_ip not in", values, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpBetween(String value1, String value2) {
            addCriterion("create_ip between", value1, value2, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpNotBetween(String value1, String value2) {
            addCriterion("create_ip not between", value1, value2, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateInputterIsNull() {
            addCriterion("create_inputter is null");
            return (Criteria) this;
        }

        public Criteria andCreateInputterIsNotNull() {
            addCriterion("create_inputter is not null");
            return (Criteria) this;
        }

        public Criteria andCreateInputterEqualTo(String value) {
            addCriterion("create_inputter =", value, "createInputter");
            return (Criteria) this;
        }

        public Criteria andCreateInputterNotEqualTo(String value) {
            addCriterion("create_inputter <>", value, "createInputter");
            return (Criteria) this;
        }

        public Criteria andCreateInputterGreaterThan(String value) {
            addCriterion("create_inputter >", value, "createInputter");
            return (Criteria) this;
        }

        public Criteria andCreateInputterGreaterThanOrEqualTo(String value) {
            addCriterion("create_inputter >=", value, "createInputter");
            return (Criteria) this;
        }

        public Criteria andCreateInputterLessThan(String value) {
            addCriterion("create_inputter <", value, "createInputter");
            return (Criteria) this;
        }

        public Criteria andCreateInputterLessThanOrEqualTo(String value) {
            addCriterion("create_inputter <=", value, "createInputter");
            return (Criteria) this;
        }

        public Criteria andCreateInputterLike(String value) {
            addCriterion("create_inputter like", value, "createInputter");
            return (Criteria) this;
        }

        public Criteria andCreateInputterNotLike(String value) {
            addCriterion("create_inputter not like", value, "createInputter");
            return (Criteria) this;
        }

        public Criteria andCreateInputterIn(List<String> values) {
            addCriterion("create_inputter in", values, "createInputter");
            return (Criteria) this;
        }

        public Criteria andCreateInputterNotIn(List<String> values) {
            addCriterion("create_inputter not in", values, "createInputter");
            return (Criteria) this;
        }

        public Criteria andCreateInputterBetween(String value1, String value2) {
            addCriterion("create_inputter between", value1, value2, "createInputter");
            return (Criteria) this;
        }

        public Criteria andCreateInputterNotBetween(String value1, String value2) {
            addCriterion("create_inputter not between", value1, value2, "createInputter");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidIsNull() {
            addCriterion("create_pgmid is null");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidIsNotNull() {
            addCriterion("create_pgmid is not null");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidEqualTo(String value) {
            addCriterion("create_pgmid =", value, "createPgmid");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidNotEqualTo(String value) {
            addCriterion("create_pgmid <>", value, "createPgmid");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidGreaterThan(String value) {
            addCriterion("create_pgmid >", value, "createPgmid");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidGreaterThanOrEqualTo(String value) {
            addCriterion("create_pgmid >=", value, "createPgmid");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidLessThan(String value) {
            addCriterion("create_pgmid <", value, "createPgmid");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidLessThanOrEqualTo(String value) {
            addCriterion("create_pgmid <=", value, "createPgmid");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidLike(String value) {
            addCriterion("create_pgmid like", value, "createPgmid");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidNotLike(String value) {
            addCriterion("create_pgmid not like", value, "createPgmid");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidIn(List<String> values) {
            addCriterion("create_pgmid in", values, "createPgmid");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidNotIn(List<String> values) {
            addCriterion("create_pgmid not in", values, "createPgmid");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidBetween(String value1, String value2) {
            addCriterion("create_pgmid between", value1, value2, "createPgmid");
            return (Criteria) this;
        }

        public Criteria andCreatePgmidNotBetween(String value1, String value2) {
            addCriterion("create_pgmid not between", value1, value2, "createPgmid");
            return (Criteria) this;
        }

        public Criteria andReviseDatetimeIsNull() {
            addCriterion("revise_datetime is null");
            return (Criteria) this;
        }

        public Criteria andReviseDatetimeIsNotNull() {
            addCriterion("revise_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andReviseDatetimeEqualTo(LocalDateTime value) {
            addCriterion("revise_datetime =", value, "reviseDatetime");
            return (Criteria) this;
        }

        public Criteria andReviseDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("revise_datetime <>", value, "reviseDatetime");
            return (Criteria) this;
        }

        public Criteria andReviseDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("revise_datetime >", value, "reviseDatetime");
            return (Criteria) this;
        }

        public Criteria andReviseDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("revise_datetime >=", value, "reviseDatetime");
            return (Criteria) this;
        }

        public Criteria andReviseDatetimeLessThan(LocalDateTime value) {
            addCriterion("revise_datetime <", value, "reviseDatetime");
            return (Criteria) this;
        }

        public Criteria andReviseDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("revise_datetime <=", value, "reviseDatetime");
            return (Criteria) this;
        }

        public Criteria andReviseDatetimeIn(List<LocalDateTime> values) {
            addCriterion("revise_datetime in", values, "reviseDatetime");
            return (Criteria) this;
        }

        public Criteria andReviseDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("revise_datetime not in", values, "reviseDatetime");
            return (Criteria) this;
        }

        public Criteria andReviseDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("revise_datetime between", value1, value2, "reviseDatetime");
            return (Criteria) this;
        }

        public Criteria andReviseDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("revise_datetime not between", value1, value2, "reviseDatetime");
            return (Criteria) this;
        }

        public Criteria andReviseSessionIsNull() {
            addCriterion("revise_session is null");
            return (Criteria) this;
        }

        public Criteria andReviseSessionIsNotNull() {
            addCriterion("revise_session is not null");
            return (Criteria) this;
        }

        public Criteria andReviseSessionEqualTo(String value) {
            addCriterion("revise_session =", value, "reviseSession");
            return (Criteria) this;
        }

        public Criteria andReviseSessionNotEqualTo(String value) {
            addCriterion("revise_session <>", value, "reviseSession");
            return (Criteria) this;
        }

        public Criteria andReviseSessionGreaterThan(String value) {
            addCriterion("revise_session >", value, "reviseSession");
            return (Criteria) this;
        }

        public Criteria andReviseSessionGreaterThanOrEqualTo(String value) {
            addCriterion("revise_session >=", value, "reviseSession");
            return (Criteria) this;
        }

        public Criteria andReviseSessionLessThan(String value) {
            addCriterion("revise_session <", value, "reviseSession");
            return (Criteria) this;
        }

        public Criteria andReviseSessionLessThanOrEqualTo(String value) {
            addCriterion("revise_session <=", value, "reviseSession");
            return (Criteria) this;
        }

        public Criteria andReviseSessionLike(String value) {
            addCriterion("revise_session like", value, "reviseSession");
            return (Criteria) this;
        }

        public Criteria andReviseSessionNotLike(String value) {
            addCriterion("revise_session not like", value, "reviseSession");
            return (Criteria) this;
        }

        public Criteria andReviseSessionIn(List<String> values) {
            addCriterion("revise_session in", values, "reviseSession");
            return (Criteria) this;
        }

        public Criteria andReviseSessionNotIn(List<String> values) {
            addCriterion("revise_session not in", values, "reviseSession");
            return (Criteria) this;
        }

        public Criteria andReviseSessionBetween(String value1, String value2) {
            addCriterion("revise_session between", value1, value2, "reviseSession");
            return (Criteria) this;
        }

        public Criteria andReviseSessionNotBetween(String value1, String value2) {
            addCriterion("revise_session not between", value1, value2, "reviseSession");
            return (Criteria) this;
        }

        public Criteria andReviseIpIsNull() {
            addCriterion("revise_ip is null");
            return (Criteria) this;
        }

        public Criteria andReviseIpIsNotNull() {
            addCriterion("revise_ip is not null");
            return (Criteria) this;
        }

        public Criteria andReviseIpEqualTo(String value) {
            addCriterion("revise_ip =", value, "reviseIp");
            return (Criteria) this;
        }

        public Criteria andReviseIpNotEqualTo(String value) {
            addCriterion("revise_ip <>", value, "reviseIp");
            return (Criteria) this;
        }

        public Criteria andReviseIpGreaterThan(String value) {
            addCriterion("revise_ip >", value, "reviseIp");
            return (Criteria) this;
        }

        public Criteria andReviseIpGreaterThanOrEqualTo(String value) {
            addCriterion("revise_ip >=", value, "reviseIp");
            return (Criteria) this;
        }

        public Criteria andReviseIpLessThan(String value) {
            addCriterion("revise_ip <", value, "reviseIp");
            return (Criteria) this;
        }

        public Criteria andReviseIpLessThanOrEqualTo(String value) {
            addCriterion("revise_ip <=", value, "reviseIp");
            return (Criteria) this;
        }

        public Criteria andReviseIpLike(String value) {
            addCriterion("revise_ip like", value, "reviseIp");
            return (Criteria) this;
        }

        public Criteria andReviseIpNotLike(String value) {
            addCriterion("revise_ip not like", value, "reviseIp");
            return (Criteria) this;
        }

        public Criteria andReviseIpIn(List<String> values) {
            addCriterion("revise_ip in", values, "reviseIp");
            return (Criteria) this;
        }

        public Criteria andReviseIpNotIn(List<String> values) {
            addCriterion("revise_ip not in", values, "reviseIp");
            return (Criteria) this;
        }

        public Criteria andReviseIpBetween(String value1, String value2) {
            addCriterion("revise_ip between", value1, value2, "reviseIp");
            return (Criteria) this;
        }

        public Criteria andReviseIpNotBetween(String value1, String value2) {
            addCriterion("revise_ip not between", value1, value2, "reviseIp");
            return (Criteria) this;
        }

        public Criteria andReviseUserIsNull() {
            addCriterion("revise_user is null");
            return (Criteria) this;
        }

        public Criteria andReviseUserIsNotNull() {
            addCriterion("revise_user is not null");
            return (Criteria) this;
        }

        public Criteria andReviseUserEqualTo(String value) {
            addCriterion("revise_user =", value, "reviseUser");
            return (Criteria) this;
        }

        public Criteria andReviseUserNotEqualTo(String value) {
            addCriterion("revise_user <>", value, "reviseUser");
            return (Criteria) this;
        }

        public Criteria andReviseUserGreaterThan(String value) {
            addCriterion("revise_user >", value, "reviseUser");
            return (Criteria) this;
        }

        public Criteria andReviseUserGreaterThanOrEqualTo(String value) {
            addCriterion("revise_user >=", value, "reviseUser");
            return (Criteria) this;
        }

        public Criteria andReviseUserLessThan(String value) {
            addCriterion("revise_user <", value, "reviseUser");
            return (Criteria) this;
        }

        public Criteria andReviseUserLessThanOrEqualTo(String value) {
            addCriterion("revise_user <=", value, "reviseUser");
            return (Criteria) this;
        }

        public Criteria andReviseUserLike(String value) {
            addCriterion("revise_user like", value, "reviseUser");
            return (Criteria) this;
        }

        public Criteria andReviseUserNotLike(String value) {
            addCriterion("revise_user not like", value, "reviseUser");
            return (Criteria) this;
        }

        public Criteria andReviseUserIn(List<String> values) {
            addCriterion("revise_user in", values, "reviseUser");
            return (Criteria) this;
        }

        public Criteria andReviseUserNotIn(List<String> values) {
            addCriterion("revise_user not in", values, "reviseUser");
            return (Criteria) this;
        }

        public Criteria andReviseUserBetween(String value1, String value2) {
            addCriterion("revise_user between", value1, value2, "reviseUser");
            return (Criteria) this;
        }

        public Criteria andReviseUserNotBetween(String value1, String value2) {
            addCriterion("revise_user not between", value1, value2, "reviseUser");
            return (Criteria) this;
        }

        public Criteria andReviseInputterIsNull() {
            addCriterion("revise_inputter is null");
            return (Criteria) this;
        }

        public Criteria andReviseInputterIsNotNull() {
            addCriterion("revise_inputter is not null");
            return (Criteria) this;
        }

        public Criteria andReviseInputterEqualTo(String value) {
            addCriterion("revise_inputter =", value, "reviseInputter");
            return (Criteria) this;
        }

        public Criteria andReviseInputterNotEqualTo(String value) {
            addCriterion("revise_inputter <>", value, "reviseInputter");
            return (Criteria) this;
        }

        public Criteria andReviseInputterGreaterThan(String value) {
            addCriterion("revise_inputter >", value, "reviseInputter");
            return (Criteria) this;
        }

        public Criteria andReviseInputterGreaterThanOrEqualTo(String value) {
            addCriterion("revise_inputter >=", value, "reviseInputter");
            return (Criteria) this;
        }

        public Criteria andReviseInputterLessThan(String value) {
            addCriterion("revise_inputter <", value, "reviseInputter");
            return (Criteria) this;
        }

        public Criteria andReviseInputterLessThanOrEqualTo(String value) {
            addCriterion("revise_inputter <=", value, "reviseInputter");
            return (Criteria) this;
        }

        public Criteria andReviseInputterLike(String value) {
            addCriterion("revise_inputter like", value, "reviseInputter");
            return (Criteria) this;
        }

        public Criteria andReviseInputterNotLike(String value) {
            addCriterion("revise_inputter not like", value, "reviseInputter");
            return (Criteria) this;
        }

        public Criteria andReviseInputterIn(List<String> values) {
            addCriterion("revise_inputter in", values, "reviseInputter");
            return (Criteria) this;
        }

        public Criteria andReviseInputterNotIn(List<String> values) {
            addCriterion("revise_inputter not in", values, "reviseInputter");
            return (Criteria) this;
        }

        public Criteria andReviseInputterBetween(String value1, String value2) {
            addCriterion("revise_inputter between", value1, value2, "reviseInputter");
            return (Criteria) this;
        }

        public Criteria andReviseInputterNotBetween(String value1, String value2) {
            addCriterion("revise_inputter not between", value1, value2, "reviseInputter");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidIsNull() {
            addCriterion("revise_pgmid is null");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidIsNotNull() {
            addCriterion("revise_pgmid is not null");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidEqualTo(String value) {
            addCriterion("revise_pgmid =", value, "revisePgmid");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidNotEqualTo(String value) {
            addCriterion("revise_pgmid <>", value, "revisePgmid");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidGreaterThan(String value) {
            addCriterion("revise_pgmid >", value, "revisePgmid");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidGreaterThanOrEqualTo(String value) {
            addCriterion("revise_pgmid >=", value, "revisePgmid");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidLessThan(String value) {
            addCriterion("revise_pgmid <", value, "revisePgmid");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidLessThanOrEqualTo(String value) {
            addCriterion("revise_pgmid <=", value, "revisePgmid");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidLike(String value) {
            addCriterion("revise_pgmid like", value, "revisePgmid");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidNotLike(String value) {
            addCriterion("revise_pgmid not like", value, "revisePgmid");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidIn(List<String> values) {
            addCriterion("revise_pgmid in", values, "revisePgmid");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidNotIn(List<String> values) {
            addCriterion("revise_pgmid not in", values, "revisePgmid");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidBetween(String value1, String value2) {
            addCriterion("revise_pgmid between", value1, value2, "revisePgmid");
            return (Criteria) this;
        }

        public Criteria andRevisePgmidNotBetween(String value1, String value2) {
            addCriterion("revise_pgmid not between", value1, value2, "revisePgmid");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(LocalDateTime value) {
            addCriterion("update_datetime =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_datetime <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("update_datetime >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_datetime >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(LocalDateTime value) {
            addCriterion("update_datetime <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_datetime <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<LocalDateTime> values) {
            addCriterion("update_datetime in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_datetime not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_datetime between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_datetime not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionIsNull() {
            addCriterion("update_session is null");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionIsNotNull() {
            addCriterion("update_session is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionEqualTo(String value) {
            addCriterion("update_session =", value, "updateSession");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionNotEqualTo(String value) {
            addCriterion("update_session <>", value, "updateSession");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionGreaterThan(String value) {
            addCriterion("update_session >", value, "updateSession");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionGreaterThanOrEqualTo(String value) {
            addCriterion("update_session >=", value, "updateSession");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionLessThan(String value) {
            addCriterion("update_session <", value, "updateSession");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionLessThanOrEqualTo(String value) {
            addCriterion("update_session <=", value, "updateSession");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionLike(String value) {
            addCriterion("update_session like", value, "updateSession");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionNotLike(String value) {
            addCriterion("update_session not like", value, "updateSession");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionIn(List<String> values) {
            addCriterion("update_session in", values, "updateSession");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionNotIn(List<String> values) {
            addCriterion("update_session not in", values, "updateSession");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionBetween(String value1, String value2) {
            addCriterion("update_session between", value1, value2, "updateSession");
            return (Criteria) this;
        }

        public Criteria andUpdateSessionNotBetween(String value1, String value2) {
            addCriterion("update_session not between", value1, value2, "updateSession");
            return (Criteria) this;
        }

        public Criteria andUpdateIpIsNull() {
            addCriterion("update_ip is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIpIsNotNull() {
            addCriterion("update_ip is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIpEqualTo(String value) {
            addCriterion("update_ip =", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andUpdateIpNotEqualTo(String value) {
            addCriterion("update_ip <>", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andUpdateIpGreaterThan(String value) {
            addCriterion("update_ip >", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andUpdateIpGreaterThanOrEqualTo(String value) {
            addCriterion("update_ip >=", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andUpdateIpLessThan(String value) {
            addCriterion("update_ip <", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andUpdateIpLessThanOrEqualTo(String value) {
            addCriterion("update_ip <=", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andUpdateIpLike(String value) {
            addCriterion("update_ip like", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andUpdateIpNotLike(String value) {
            addCriterion("update_ip not like", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andUpdateIpIn(List<String> values) {
            addCriterion("update_ip in", values, "updateIp");
            return (Criteria) this;
        }

        public Criteria andUpdateIpNotIn(List<String> values) {
            addCriterion("update_ip not in", values, "updateIp");
            return (Criteria) this;
        }

        public Criteria andUpdateIpBetween(String value1, String value2) {
            addCriterion("update_ip between", value1, value2, "updateIp");
            return (Criteria) this;
        }

        public Criteria andUpdateIpNotBetween(String value1, String value2) {
            addCriterion("update_ip not between", value1, value2, "updateIp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterIsNull() {
            addCriterion("update_inputter is null");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterIsNotNull() {
            addCriterion("update_inputter is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterEqualTo(String value) {
            addCriterion("update_inputter =", value, "updateInputter");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterNotEqualTo(String value) {
            addCriterion("update_inputter <>", value, "updateInputter");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterGreaterThan(String value) {
            addCriterion("update_inputter >", value, "updateInputter");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterGreaterThanOrEqualTo(String value) {
            addCriterion("update_inputter >=", value, "updateInputter");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterLessThan(String value) {
            addCriterion("update_inputter <", value, "updateInputter");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterLessThanOrEqualTo(String value) {
            addCriterion("update_inputter <=", value, "updateInputter");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterLike(String value) {
            addCriterion("update_inputter like", value, "updateInputter");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterNotLike(String value) {
            addCriterion("update_inputter not like", value, "updateInputter");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterIn(List<String> values) {
            addCriterion("update_inputter in", values, "updateInputter");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterNotIn(List<String> values) {
            addCriterion("update_inputter not in", values, "updateInputter");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterBetween(String value1, String value2) {
            addCriterion("update_inputter between", value1, value2, "updateInputter");
            return (Criteria) this;
        }

        public Criteria andUpdateInputterNotBetween(String value1, String value2) {
            addCriterion("update_inputter not between", value1, value2, "updateInputter");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidIsNull() {
            addCriterion("update_pgmid is null");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidIsNotNull() {
            addCriterion("update_pgmid is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidEqualTo(String value) {
            addCriterion("update_pgmid =", value, "updatePgmid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidNotEqualTo(String value) {
            addCriterion("update_pgmid <>", value, "updatePgmid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidGreaterThan(String value) {
            addCriterion("update_pgmid >", value, "updatePgmid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidGreaterThanOrEqualTo(String value) {
            addCriterion("update_pgmid >=", value, "updatePgmid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidLessThan(String value) {
            addCriterion("update_pgmid <", value, "updatePgmid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidLessThanOrEqualTo(String value) {
            addCriterion("update_pgmid <=", value, "updatePgmid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidLike(String value) {
            addCriterion("update_pgmid like", value, "updatePgmid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidNotLike(String value) {
            addCriterion("update_pgmid not like", value, "updatePgmid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidIn(List<String> values) {
            addCriterion("update_pgmid in", values, "updatePgmid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidNotIn(List<String> values) {
            addCriterion("update_pgmid not in", values, "updatePgmid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidBetween(String value1, String value2) {
            addCriterion("update_pgmid between", value1, value2, "updatePgmid");
            return (Criteria) this;
        }

        public Criteria andUpdatePgmidNotBetween(String value1, String value2) {
            addCriterion("update_pgmid not between", value1, value2, "updatePgmid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table njt_005.t_shipping_package
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}