package com.example.entity;

import java.time.LocalDateTime;

public class TShippingPackage extends TShippingPackageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.shipping_no
     *
     * @mbg.generated
     */
    private String shippingNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.total_coil_quantity
     *
     * @mbg.generated
     */
    private Integer totalCoilQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.delete_flg
     *
     * @mbg.generated
     */
    private String deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.create_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.create_session
     *
     * @mbg.generated
     */
    private String createSession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.create_ip
     *
     * @mbg.generated
     */
    private String createIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.create_inputter
     *
     * @mbg.generated
     */
    private String createInputter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.create_pgmid
     *
     * @mbg.generated
     */
    private String createPgmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.revise_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime reviseDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.revise_session
     *
     * @mbg.generated
     */
    private String reviseSession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.revise_ip
     *
     * @mbg.generated
     */
    private String reviseIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.revise_user
     *
     * @mbg.generated
     */
    private String reviseUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.revise_inputter
     *
     * @mbg.generated
     */
    private String reviseInputter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.revise_pgmid
     *
     * @mbg.generated
     */
    private String revisePgmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.update_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.update_session
     *
     * @mbg.generated
     */
    private String updateSession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.update_ip
     *
     * @mbg.generated
     */
    private String updateIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.update_inputter
     *
     * @mbg.generated
     */
    private String updateInputter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.update_pgmid
     *
     * @mbg.generated
     */
    private String updatePgmid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.shipping_no
     *
     * @return the value of njt_005.t_shipping_package.shipping_no
     *
     * @mbg.generated
     */
    public String getShippingNo() {
        return shippingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.shipping_no
     *
     * @param shippingNo the value for njt_005.t_shipping_package.shipping_no
     *
     * @mbg.generated
     */
    public void setShippingNo(String shippingNo) {
        this.shippingNo = shippingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.total_coil_quantity
     *
     * @return the value of njt_005.t_shipping_package.total_coil_quantity
     *
     * @mbg.generated
     */
    public Integer getTotalCoilQuantity() {
        return totalCoilQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.total_coil_quantity
     *
     * @param totalCoilQuantity the value for njt_005.t_shipping_package.total_coil_quantity
     *
     * @mbg.generated
     */
    public void setTotalCoilQuantity(Integer totalCoilQuantity) {
        this.totalCoilQuantity = totalCoilQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.delete_flg
     *
     * @return the value of njt_005.t_shipping_package.delete_flg
     *
     * @mbg.generated
     */
    public String getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.delete_flg
     *
     * @param deleteFlg the value for njt_005.t_shipping_package.delete_flg
     *
     * @mbg.generated
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.create_datetime
     *
     * @return the value of njt_005.t_shipping_package.create_datetime
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.create_datetime
     *
     * @param createDatetime the value for njt_005.t_shipping_package.create_datetime
     *
     * @mbg.generated
     */
    public void setCreateDatetime(LocalDateTime createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.create_session
     *
     * @return the value of njt_005.t_shipping_package.create_session
     *
     * @mbg.generated
     */
    public String getCreateSession() {
        return createSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.create_session
     *
     * @param createSession the value for njt_005.t_shipping_package.create_session
     *
     * @mbg.generated
     */
    public void setCreateSession(String createSession) {
        this.createSession = createSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.create_ip
     *
     * @return the value of njt_005.t_shipping_package.create_ip
     *
     * @mbg.generated
     */
    public String getCreateIp() {
        return createIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.create_ip
     *
     * @param createIp the value for njt_005.t_shipping_package.create_ip
     *
     * @mbg.generated
     */
    public void setCreateIp(String createIp) {
        this.createIp = createIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.create_user
     *
     * @return the value of njt_005.t_shipping_package.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.create_user
     *
     * @param createUser the value for njt_005.t_shipping_package.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.create_inputter
     *
     * @return the value of njt_005.t_shipping_package.create_inputter
     *
     * @mbg.generated
     */
    public String getCreateInputter() {
        return createInputter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.create_inputter
     *
     * @param createInputter the value for njt_005.t_shipping_package.create_inputter
     *
     * @mbg.generated
     */
    public void setCreateInputter(String createInputter) {
        this.createInputter = createInputter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.create_pgmid
     *
     * @return the value of njt_005.t_shipping_package.create_pgmid
     *
     * @mbg.generated
     */
    public String getCreatePgmid() {
        return createPgmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.create_pgmid
     *
     * @param createPgmid the value for njt_005.t_shipping_package.create_pgmid
     *
     * @mbg.generated
     */
    public void setCreatePgmid(String createPgmid) {
        this.createPgmid = createPgmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.revise_datetime
     *
     * @return the value of njt_005.t_shipping_package.revise_datetime
     *
     * @mbg.generated
     */
    public LocalDateTime getReviseDatetime() {
        return reviseDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.revise_datetime
     *
     * @param reviseDatetime the value for njt_005.t_shipping_package.revise_datetime
     *
     * @mbg.generated
     */
    public void setReviseDatetime(LocalDateTime reviseDatetime) {
        this.reviseDatetime = reviseDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.revise_session
     *
     * @return the value of njt_005.t_shipping_package.revise_session
     *
     * @mbg.generated
     */
    public String getReviseSession() {
        return reviseSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.revise_session
     *
     * @param reviseSession the value for njt_005.t_shipping_package.revise_session
     *
     * @mbg.generated
     */
    public void setReviseSession(String reviseSession) {
        this.reviseSession = reviseSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.revise_ip
     *
     * @return the value of njt_005.t_shipping_package.revise_ip
     *
     * @mbg.generated
     */
    public String getReviseIp() {
        return reviseIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.revise_ip
     *
     * @param reviseIp the value for njt_005.t_shipping_package.revise_ip
     *
     * @mbg.generated
     */
    public void setReviseIp(String reviseIp) {
        this.reviseIp = reviseIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.revise_user
     *
     * @return the value of njt_005.t_shipping_package.revise_user
     *
     * @mbg.generated
     */
    public String getReviseUser() {
        return reviseUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.revise_user
     *
     * @param reviseUser the value for njt_005.t_shipping_package.revise_user
     *
     * @mbg.generated
     */
    public void setReviseUser(String reviseUser) {
        this.reviseUser = reviseUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.revise_inputter
     *
     * @return the value of njt_005.t_shipping_package.revise_inputter
     *
     * @mbg.generated
     */
    public String getReviseInputter() {
        return reviseInputter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.revise_inputter
     *
     * @param reviseInputter the value for njt_005.t_shipping_package.revise_inputter
     *
     * @mbg.generated
     */
    public void setReviseInputter(String reviseInputter) {
        this.reviseInputter = reviseInputter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.revise_pgmid
     *
     * @return the value of njt_005.t_shipping_package.revise_pgmid
     *
     * @mbg.generated
     */
    public String getRevisePgmid() {
        return revisePgmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.revise_pgmid
     *
     * @param revisePgmid the value for njt_005.t_shipping_package.revise_pgmid
     *
     * @mbg.generated
     */
    public void setRevisePgmid(String revisePgmid) {
        this.revisePgmid = revisePgmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.update_datetime
     *
     * @return the value of njt_005.t_shipping_package.update_datetime
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.update_datetime
     *
     * @param updateDatetime the value for njt_005.t_shipping_package.update_datetime
     *
     * @mbg.generated
     */
    public void setUpdateDatetime(LocalDateTime updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.update_session
     *
     * @return the value of njt_005.t_shipping_package.update_session
     *
     * @mbg.generated
     */
    public String getUpdateSession() {
        return updateSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.update_session
     *
     * @param updateSession the value for njt_005.t_shipping_package.update_session
     *
     * @mbg.generated
     */
    public void setUpdateSession(String updateSession) {
        this.updateSession = updateSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.update_ip
     *
     * @return the value of njt_005.t_shipping_package.update_ip
     *
     * @mbg.generated
     */
    public String getUpdateIp() {
        return updateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.update_ip
     *
     * @param updateIp the value for njt_005.t_shipping_package.update_ip
     *
     * @mbg.generated
     */
    public void setUpdateIp(String updateIp) {
        this.updateIp = updateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.update_user
     *
     * @return the value of njt_005.t_shipping_package.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.update_user
     *
     * @param updateUser the value for njt_005.t_shipping_package.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.update_inputter
     *
     * @return the value of njt_005.t_shipping_package.update_inputter
     *
     * @mbg.generated
     */
    public String getUpdateInputter() {
        return updateInputter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.update_inputter
     *
     * @param updateInputter the value for njt_005.t_shipping_package.update_inputter
     *
     * @mbg.generated
     */
    public void setUpdateInputter(String updateInputter) {
        this.updateInputter = updateInputter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.update_pgmid
     *
     * @return the value of njt_005.t_shipping_package.update_pgmid
     *
     * @mbg.generated
     */
    public String getUpdatePgmid() {
        return updatePgmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.update_pgmid
     *
     * @param updatePgmid the value for njt_005.t_shipping_package.update_pgmid
     *
     * @mbg.generated
     */
    public void setUpdatePgmid(String updatePgmid) {
        this.updatePgmid = updatePgmid;
    }
}