package com.example.entity;

public class TShippingPackageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.shipping_instruction_no
     *
     * @mbg.generated
     */
    private Integer shippingInstructionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.wno
     *
     * @mbg.generated
     */
    private String wno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column njt_005.t_shipping_package.package_no
     *
     * @mbg.generated
     */
    private String packageNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.shipping_instruction_no
     *
     * @return the value of njt_005.t_shipping_package.shipping_instruction_no
     *
     * @mbg.generated
     */
    public Integer getShippingInstructionNo() {
        return shippingInstructionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.shipping_instruction_no
     *
     * @param shippingInstructionNo the value for njt_005.t_shipping_package.shipping_instruction_no
     *
     * @mbg.generated
     */
    public void setShippingInstructionNo(Integer shippingInstructionNo) {
        this.shippingInstructionNo = shippingInstructionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.wno
     *
     * @return the value of njt_005.t_shipping_package.wno
     *
     * @mbg.generated
     */
    public String getWno() {
        return wno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.wno
     *
     * @param wno the value for njt_005.t_shipping_package.wno
     *
     * @mbg.generated
     */
    public void setWno(String wno) {
        this.wno = wno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column njt_005.t_shipping_package.package_no
     *
     * @return the value of njt_005.t_shipping_package.package_no
     *
     * @mbg.generated
     */
    public String getPackageNo() {
        return packageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column njt_005.t_shipping_package.package_no
     *
     * @param packageNo the value for njt_005.t_shipping_package.package_no
     *
     * @mbg.generated
     */
    public void setPackageNo(String packageNo) {
        this.packageNo = packageNo;
    }
}